# Generated by Django 2.1.7 on 2019-03-08 23:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.IntegerField(default=uuid.UUID('951acf16-0e53-4a3f-8cea-c2f90e23f2c7'), primary_key=True, serialize=False)),
                ('size', models.IntegerField(default=0)),
                ('timeIn', models.DateTimeField(default=None, null=True)),
                ('timeEnd', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DropOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SellPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(default='', editable=False, max_length=100, unique=True)),
                ('role', models.IntegerField(default=1)),
                ('sellPoint', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.SellPoint', verbose_name='selling point (shop assistant)')),
            ],
        ),
        migrations.AddField(
            model_name='sellpoint',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Station'),
        ),
        migrations.AddField(
            model_name='dropoff',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Station'),
        ),
        migrations.AddField(
            model_name='cup',
            name='dropOff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.DropOff'),
        ),
        migrations.AddField(
            model_name='cup',
            name='sellPoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.SellPoint'),
        ),
        migrations.AddField(
            model_name='cup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
    ]
