# Generated by Django 2.1.7 on 2019-03-09 01:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='id',
            field=models.IntegerField(default=uuid.UUID('efaad943-8d81-4607-80b1-4ebdebc3b4fb'), primary_key=True, serialize=False),
        ),
    ]
