# Generated by Django 2.1.7 on 2019-03-09 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 12, 54, 16, 735193), null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sellPoint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.SellPoint', verbose_name='selling point (shop assistant)'),
        ),
    ]
