# Generated by Django 2.1.7 on 2019-03-09 01:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='id',
            field=models.IntegerField(default=uuid.UUID('6d68e08a-30da-428c-93de-a170d651e2fb'), primary_key=True, serialize=False),
        ),
    ]
