# Generated by Django 2.1.7 on 2019-03-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='cups_current',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='station',
            name='cups_desired',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='movement',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='website.Station'),
        ),
        migrations.AddField(
            model_name='movement',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='website.Station'),
        ),
    ]
