# Generated by Django 2.1.7 on 2019-03-09 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190309_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 12, 6, 40, 461213), null=True),
        ),
    ]
