# Generated by Django 2.1.7 on 2019-03-09 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190309_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='id',
            field=models.IntegerField(default=uuid.UUID('b8b5fcab-ecfc-4d3f-a36b-23390c63540c'), primary_key=True, serialize=False),
        ),
    ]
