# Generated by Django 2.1.7 on 2019-03-09 01:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190309_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='id',
            field=models.IntegerField(default=uuid.UUID('e273c13f-0d2a-4039-989f-63beaae7054c'), primary_key=True, serialize=False),
        ),
    ]
