# Generated by Django 2.1.7 on 2019-03-09 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190309_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='id',
            field=models.IntegerField(default=uuid.UUID('644f39d6-5f37-434d-84b5-7f91260b708c'), primary_key=True, serialize=False),
        ),
    ]
