# Generated by Django 2.1.7 on 2019-03-09 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190309_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 12, 8, 33, 564710), null=True),
        ),
    ]
