# Generated by Django 2.1.7 on 2019-03-09 12:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190309_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dropoff',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.DropOff', verbose_name='dropoff point (return machine)'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 12, 30, 56, 75784), null=True),
        ),
    ]
