# Generated by Django 2.1.7 on 2019-03-09 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190309_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropoff',
            name='cups_current',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='cup',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 12, 33, 27, 860508), null=True),
        ),
    ]
