# Generated by Django 2.1.7 on 2019-03-09 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190309_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dropoff',
            new_name='dropOff',
        ),
        migrations.AlterField(
            model_name='cup',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 12, 35, 25, 664278), null=True),
        ),
    ]
