# Generated by Django 2.1.7 on 2019-03-09 13:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190309_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.DateTimeField(default=datetime.datetime(2019, 3, 9, 13, 44, 3, 257131), null=True)),
                ('time2', models.DateTimeField(default=None, null=True)),
                ('time3', models.DateTimeField(default=None, null=True)),
                ('time4', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cup',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 13, 44, 3, 256532), null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='cup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Cup', verbose_name='cup'),
        ),
        migrations.AddField(
            model_name='history',
            name='dropOff',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.DropOff', verbose_name='cup dropped off'),
        ),
        migrations.AddField(
            model_name='history',
            name='sellPoint',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.SellPoint', verbose_name='selling point (shop assistant)'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
